create table public.image (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  stack bigint null,
  path text null,
  orb_features bit(256) null,
  person bigint null,
  title text null,
  flag_status public.flag_status null,
  flagged_by bigint null,
  x_features extensions.vector null,
  exclude boolean null default false,
  image_embedding extensions.vector null,
  image_embedding_hq extensions.vector null,
  constraint image_pkey primary key (id),
  constraint image_flagged_by_fkey foreign KEY (flagged_by) references "user" (id),
  constraint image_person_fkey foreign KEY (person) references person (id),
  constraint image_stack_fkey foreign KEY (stack) references stack (id)
) TABLESPACE pg_default;

create table public.person (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  first_name text null,
  last_name text null,
  folder text null,
  constraint person_pkey primary key (id)
) TABLESPACE pg_default;

create table public.stack (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  person bigint null,
  name text null,
  meta_data text null,
  thumbnail bigint null,
  constraint collection_pkey primary key (id),
  constraint collection_person_fkey foreign KEY (person) references person (id),
  constraint collection_thumbnail_fkey foreign KEY (thumbnail) references image (id)
) TABLESPACE pg_default;

create table public.user (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  constraint user_pkey primary key (id)
) TABLESPACE pg_default;
